// pages/brick-types.tsx
import React, { useState, useEffect } from 'react';
import { Layout } from '../components/Layout/Layout';
import { Button } from '../components/Common/Button';
import { BrickTypeTable } from '../components/BrickTypes/BrickTypeTable';
import { BrickTypeModal } from '../components/BrickTypes/BrickTypeModal';
import { BrickType } from '../types';

// Mock data based on the provided table
const mockBrickTypes: BrickType[] = [
  {
      id: 1,
      name: '300x600mm Porcelain mài bóng',
      size: '300x600mm',
      type: 'porcelain',
      workshop_id: 1,
      production_line_id: 1,
      workshop_name: 'Phân xưởng 1',
      production_line_name: 'Dây chuyền 1',
      chu_ky_khoan: 50,
      san_luong_ra_lo_per_day: 10037,
      san_luong_chinh_pham_per_day: 9590,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 273300,
      san_luong_khoan_31_ngay: 282900,
      cong_khoan_giam_chu_ky: 98,
      giam_khoan_tang_chu_ky: 147,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 2,
      name: '300x600mm Granite dày 12mm',
      size: '300x600mm',
      type: 'granite',
      workshop_id: 1,
      production_line_id: 1,
      workshop_name: 'Phân xưởng 1',
      production_line_name: 'Dây chuyền 1',
      chu_ky_khoan: 52,
      san_luong_ra_lo_per_day: 9665,
      san_luong_chinh_pham_per_day: 9230,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 263100,
      san_luong_khoan_31_ngay: 272300,
      cong_khoan_giam_chu_ky: 90,
      giam_khoan_tang_chu_ky: 136,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 3,
      name: '400x800mm Granite mài bóng',
      size: '400x800mm',
      type: 'granite',
      workshop_id: 1,
      production_line_id: 1,
      workshop_name: 'Phân xưởng 1',
      production_line_name: 'Dây chuyền 1',
      chu_ky_khoan: 48,
      san_luong_ra_lo_per_day: 11792,
      san_luong_chinh_pham_per_day: 11260,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 320900,
      san_luong_khoan_31_ngay: 332200,
      cong_khoan_giam_chu_ky: 120,
      giam_khoan_tang_chu_ky: 180,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 4,
      name: '400x800mm Granite dày 12mm',
      size: '400x800mm',
      type: 'granite',
      workshop_id: 1,
      production_line_id: 1,
      workshop_name: 'Phân xưởng 1',
      production_line_name: 'Dây chuyền 1',
      chu_ky_khoan: 50,
      san_luong_ra_lo_per_day: 11321,
      san_luong_chinh_pham_per_day: 10810,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 308100,
      san_luong_khoan_31_ngay: 318900,
      cong_khoan_giam_chu_ky: 110,
      giam_khoan_tang_chu_ky: 165,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 5,
      name: '400x600mm Granite dày',
      size: '400x600mm',
      type: 'granite',
      workshop_id: 1,
      production_line_id: 1,
      workshop_name: 'Phân xưởng 1',
      production_line_name: 'Dây chuyền 1',
      chu_ky_khoan: 50,
      san_luong_ra_lo_per_day: 11454,
      san_luong_chinh_pham_per_day: 11000,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 313500,
      san_luong_khoan_31_ngay: 324500,
      cong_khoan_giam_chu_ky: 112,
      giam_khoan_tang_chu_ky: 168,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 6,
      name: '800x800mm Porcelain',
      size: '800x800mm',
      type: 'porcelain',
      workshop_id: 1,
      production_line_id: 1,
      workshop_name: 'Phân xưởng 1',
      production_line_name: 'Dây chuyền 1',
      chu_ky_khoan: 44,
      san_luong_ra_lo_per_day: 13122,
      san_luong_chinh_pham_per_day: 12600,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 359100,
      san_luong_khoan_31_ngay: 371700,
      cong_khoan_giam_chu_ky: 146,
      giam_khoan_tang_chu_ky: 220,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 7,
      name: '600x600mm Porcelain',
      size: '600x600mm',
      type: 'porcelain',
      workshop_id: 1,
      production_line_id: 1,
      workshop_name: 'Phân xưởng 1',
      production_line_name: 'Dây chuyền 1',
      chu_ky_khoan: 44,
      san_luong_ra_lo_per_day: 12997,
      san_luong_chinh_pham_per_day: 12480,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 355700,
      san_luong_khoan_31_ngay: 368200,
      cong_khoan_giam_chu_ky: 145,
      giam_khoan_tang_chu_ky: 218,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 8,
      name: '600x600mm Semi men bóng',
      size: '600x600mm',
      type: 'semi_porcelain',
      workshop_id: 1,
      production_line_id: 1,
      workshop_name: 'Phân xưởng 1',
      production_line_name: 'Dây chuyền 1',
      chu_ky_khoan: 43,
      san_luong_ra_lo_per_day: 13299,
      san_luong_chinh_pham_per_day: 12770,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 363900,
      san_luong_khoan_31_ngay: 376700,
      cong_khoan_giam_chu_ky: 152,
      giam_khoan_tang_chu_ky: 228,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 9,
      name: '600x600mm Porcelain',
      size: '600x600mm',
      type: 'porcelain',
      workshop_id: 1,
      production_line_id: 2,
      workshop_name: 'Phân xưởng 1',
      production_line_name: 'Dây chuyền 2',
      chu_ky_khoan: 42,
      san_luong_ra_lo_per_day: 15953,
      san_luong_chinh_pham_per_day: 15310,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 436300,
      san_luong_khoan_31_ngay: 451600,
      cong_khoan_giam_chu_ky: 187,
      giam_khoan_tang_chu_ky: 280,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 10,
      name: '600x600mm Semi men bóng',
      size: '600x600mm',
      type: 'semi_porcelain',
      workshop_id: 1,
      production_line_id: 2,
      workshop_name: 'Phân xưởng 1',
      production_line_name: 'Dây chuyền 2',
      chu_ky_khoan: 41,
      san_luong_ra_lo_per_day: 16342,
      san_luong_chinh_pham_per_day: 15690,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 447200,
      san_luong_khoan_31_ngay: 462900,
      cong_khoan_giam_chu_ky: 196,
      giam_khoan_tang_chu_ky: 294,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 11,
      name: '800x800mm Porcelain',
      size: '800x800mm',
      type: 'porcelain',
      workshop_id: 1,
      production_line_id: 2,
      workshop_name: 'Phân xưởng 1',
      production_line_name: 'Dây chuyền 2',
      chu_ky_khoan: 47,
      san_luong_ra_lo_per_day: 14335,
      san_luong_chinh_pham_per_day: 13760,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 392200,
      san_luong_khoan_31_ngay: 405900,
      cong_khoan_giam_chu_ky: 150,
      giam_khoan_tang_chu_ky: 224,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 12,
      name: '600x600mm Granite dày 12mm',
      size: '600x600mm',
      type: 'granite',
      workshop_id: 1,
      production_line_id: 2,
      workshop_name: 'Phân xưởng 1',
      production_line_name: 'Dây chuyền 2',
      chu_ky_khoan: 45,
      san_luong_ra_lo_per_day: 14889,
      san_luong_chinh_pham_per_day: 14290,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 407300,
      san_luong_khoan_31_ngay: 421600,
      cong_khoan_giam_chu_ky: 162,
      giam_khoan_tang_chu_ky: 244,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 13,
      name: '500x500mm Semi-Porcelain',
      size: '500x500mm',
      type: 'semi_porcelain',
      workshop_id: 1,
      production_line_id: 2,
      workshop_name: 'Phân xưởng 1',
      production_line_name: 'Dây chuyền 2',
      chu_ky_khoan: 43,
      san_luong_ra_lo_per_day: 16857,
      san_luong_chinh_pham_per_day: 16180,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 461100,
      san_luong_khoan_31_ngay: 477300,
      cong_khoan_giam_chu_ky: 193,
      giam_khoan_tang_chu_ky: 289,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 14,
      name: '500x500mm Granite dày 12mm',
      size: '500x500mm',
      type: 'granite',
      workshop_id: 1,
      production_line_id: 2,
      workshop_name: 'Phân xưởng 1',
      production_line_name: 'Dây chuyền 2',
      chu_ky_khoan: 46,
      san_luong_ra_lo_per_day: 15363,
      san_luong_chinh_pham_per_day: 14750,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 420400,
      san_luong_khoan_31_ngay: 435100,
      cong_khoan_giam_chu_ky: 164,
      giam_khoan_tang_chu_ky: 246,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 15,
      name: '500x500mm Granite dày 9,5mm',
      size: '500x500mm',
      type: 'granite',
      workshop_id: 1,
      production_line_id: 2,
      workshop_name: 'Phân xưởng 1',
      production_line_name: 'Dây chuyền 2',
      chu_ky_khoan: 43,
      san_luong_ra_lo_per_day: 16434,
      san_luong_chinh_pham_per_day: 15780,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 449700,
      san_luong_khoan_31_ngay: 465500,
      cong_khoan_giam_chu_ky: 188,
      giam_khoan_tang_chu_ky: 282,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 16,
      name: '800x800mm Porcelain',
      size: '800x800mm',
      type: 'porcelain',
      workshop_id: 2,
      production_line_id: 5,
      workshop_name: 'Phân xưởng 2',
      production_line_name: 'Dây chuyền 5',
      chu_ky_khoan: 44,
      san_luong_ra_lo_per_day: 19535,
      san_luong_chinh_pham_per_day: 18660,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 531800,
      san_luong_khoan_31_ngay: 550500,
      cong_khoan_giam_chu_ky: 217,
      giam_khoan_tang_chu_ky: 325,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 17,
      name: '600x600mm Porcelain',
      size: '600x600mm',
      type: 'porcelain',
      workshop_id: 2,
      production_line_id: 5,
      workshop_name: 'Phân xưởng 2',
      production_line_name: 'Dây chuyền 5',
      chu_ky_khoan: 47,
      san_luong_ra_lo_per_day: 18072,
      san_luong_chinh_pham_per_day: 17260,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 491900,
      san_luong_khoan_31_ngay: 509200,
      cong_khoan_giam_chu_ky: 188,
      giam_khoan_tang_chu_ky: 281,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 18,
      name: '150x800mm Porcelain',
      size: '150x800mm',
      type: 'porcelain',
      workshop_id: 2,
      production_line_id: 5,
      workshop_name: 'Phân xưởng 2',
      production_line_name: 'Dây chuyền 5',
      chu_ky_khoan: 58,
      san_luong_ra_lo_per_day: 16841,
      san_luong_chinh_pham_per_day: 16080,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 458300,
      san_luong_khoan_31_ngay: 474400,
      cong_khoan_giam_chu_ky: 141,
      giam_khoan_tang_chu_ky: 212,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 19,
      name: '1000x1000mm Granite',
      size: '1000x1000mm',
      type: 'granite',
      workshop_id: 2,
      production_line_id: 5,
      workshop_name: 'Phân xưởng 2',
      production_line_name: 'Dây chuyền 5',
      chu_ky_khoan: 63,
      san_luong_ra_lo_per_day: 11161,
      san_luong_chinh_pham_per_day: 10660,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 303800,
      san_luong_khoan_31_ngay: 314500,
      cong_khoan_giam_chu_ky: 86,
      giam_khoan_tang_chu_ky: 129,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 20,
      name: '600x1200mm Granite',
      size: '600x1200mm',
      type: 'granite',
      workshop_id: 2,
      production_line_id: 5,
      workshop_name: 'Phân xưởng 2',
      production_line_name: 'Dây chuyền 5',
      chu_ky_khoan: 60,
      san_luong_ra_lo_per_day: 13875,
      san_luong_chinh_pham_per_day: 13250,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 377600,
      san_luong_khoan_31_ngay: 390900,
      cong_khoan_giam_chu_ky: 112,
      giam_khoan_tang_chu_ky: 168,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 21,
      name: '500x500mm Ceramic Bóng',
      size: '500x500mm',
      type: 'ceramic',
      workshop_id: 2,
      production_line_id: 6,
      workshop_name: 'Phân xưởng 2',
      production_line_name: 'Dây chuyền 6',
      chu_ky_khoan: 32,
      san_luong_ra_lo_per_day: 11046,
      san_luong_chinh_pham_per_day: 10660,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 303800,
      san_luong_khoan_31_ngay: 314500,
      cong_khoan_giam_chu_ky: 172,
      giam_khoan_tang_chu_ky: 258,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 22,
      name: '500x500mm Ceramic Sân vườn',
      size: '500x500mm',
      type: 'ceramic',
      workshop_id: 2,
      production_line_id: 6,
      workshop_name: 'Phân xưởng 2',
      production_line_name: 'Dây chuyền 6',
      chu_ky_khoan: 32,
      san_luong_ra_lo_per_day: 11046,
      san_luong_chinh_pham_per_day: 10660,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 303800,
      san_luong_khoan_31_ngay: 314500,
      cong_khoan_giam_chu_ky: 172,
      giam_khoan_tang_chu_ky: 258,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 23,
      name: '500x500mm Kimsa dày 11,5mm',
      size: '500x500mm',
      type: 'kimsa',
      workshop_id: 2,
      production_line_id: 6,
      workshop_name: 'Phân xưởng 2',
      production_line_name: 'Dây chuyền 6',
      chu_ky_khoan: 47,
      san_luong_ra_lo_per_day: 7185,
      san_luong_chinh_pham_per_day: 6900,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 196700,
      san_luong_khoan_31_ngay: 203600,
      cong_khoan_giam_chu_ky: 75,
      giam_khoan_tang_chu_ky: 112,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 24,
      name: '500x500mm Kimsa dày 9,5mm',
      size: '500x500mm',
      type: 'kimsa',
      workshop_id: 2,
      production_line_id: 6,
      workshop_name: 'Phân xưởng 2',
      production_line_name: 'Dây chuyền 6',
      chu_ky_khoan: 37,
      san_luong_ra_lo_per_day: 9127,
      san_luong_chinh_pham_per_day: 8760,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 249700,
      san_luong_khoan_31_ngay: 258400,
      cong_khoan_giam_chu_ky: 122,
      giam_khoan_tang_chu_ky: 183,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 25,
      name: '500x500mm Kimsa Semi Suger',
      size: '500x500mm',
      type: 'kimsa',
      workshop_id: 2,
      production_line_id: 6,
      workshop_name: 'Phân xưởng 2',
      production_line_name: 'Dây chuyền 6',
      chu_ky_khoan: 37,
      san_luong_ra_lo_per_day: 9378,
      san_luong_chinh_pham_per_day: 9000,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 256500,
      san_luong_khoan_31_ngay: 265500,
      cong_khoan_giam_chu_ky: 125,
      giam_khoan_tang_chu_ky: 188,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 26,
      name: '400x600mm Kimsa dày 11,5mm',
      size: '400x600mm',
      type: 'kimsa',
      workshop_id: 2,
      production_line_id: 6,
      workshop_name: 'Phân xưởng 2',
      production_line_name: 'Dây chuyền 6',
      chu_ky_khoan: 48,
      san_luong_ra_lo_per_day: 7056,
      san_luong_chinh_pham_per_day: 6770,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 192900,
      san_luong_khoan_31_ngay: 199700,
      cong_khoan_giam_chu_ky: 72,
      giam_khoan_tang_chu_ky: 108,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 27,
      name: '400x600mm Kimsa dày 9,5mm',
      size: '400x600mm',
      type: 'kimsa',
      workshop_id: 2,
      production_line_id: 6,
      workshop_name: 'Phân xưởng 2',
      production_line_name: 'Dây chuyền 6',
      chu_ky_khoan: 40,
      san_luong_ra_lo_per_day: 8468,
      san_luong_chinh_pham_per_day: 8130,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 231700,
      san_luong_khoan_31_ngay: 239800,
      cong_khoan_giam_chu_ky: 104,
      giam_khoan_tang_chu_ky: 156,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  },
  {
      id: 28,
      name: '400x400mm Kimsa Semi Matt',
      size: '400x400mm',
      type: 'kimsa',
      workshop_id: 2,
      production_line_id: 6,
      workshop_name: 'Phân xưởng 2',
      production_line_name: 'Dây chuyền 6',
      chu_ky_khoan: 40,
      san_luong_ra_lo_per_day: 8519,
      san_luong_chinh_pham_per_day: 8180,
      so_ngay_tru_khoan: 1.5,
      san_luong_khoan_30_ngay: 233100,
      san_luong_khoan_31_ngay: 241300,
      cong_khoan_giam_chu_ky: 86,
      giam_khoan_tang_chu_ky: 129,
      loai_mai: 'mai_nong',
      thoi_gian_cho_mai_nguoi_hours: 0,
      ty_le_A1_khoan: 0,
      ty_le_A2_khoan: 0,
      ty_le_cat_lo_khoan: 0,
      ty_le_phe_1_khoan: 0,
      ty_le_phe_2_khoan: 0,
      ty_le_phe_huy_khoan: 0,
      don_gia_thuong_A1: 0,
      don_gia_thuong_A2: 0,
      don_gia_thuong_cat_lo: 0,
      don_gia_phat_san_luong: 0,
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
      code: ''
  }
];

// Mock workshops and production lines
const mockWorkshops = [
  { id: 1, name: 'Phân xưởng 1' },
  { id: 2, name: 'Phân xưởng 2' }
];

const mockProductionLines = [
  { id: 1, name: 'Dây chuyền 1', workshop_id: 1 },
  { id: 2, name: 'Dây chuyền 2', workshop_id: 1 },
  { id: 5, name: 'Dây chuyền 5', workshop_id: 2 },
  { id: 6, name: 'Dây chuyền 6', workshop_id: 2 }
];

export default function BrickTypesPage() {
  const [brickTypes, setBrickTypes] = useState<BrickType[]>(mockBrickTypes);
  const [showModal, setShowModal] = useState(false);
  const [editingBrickType, setEditingBrickType] = useState<BrickType | null>(null);

  const handleAddNew = () => {
    setEditingBrickType(null);
    setShowModal(true);
  };

  const handleEdit = (brickType: BrickType) => {
    setEditingBrickType(brickType);
    setShowModal(true);
  };

  const handleDelete = (id: number) => {
    if (window.confirm('Bạn có chắc chắn muốn xóa dòng gạch này?')) {
      setBrickTypes(brickTypes.filter(bt => bt.id !== id));
    }
  };

  const handleSave = (brickType: BrickType) => {
    if (editingBrickType) {
      // Update existing brick type
      setBrickTypes(brickTypes.map(bt => 
        bt.id === brickType.id ? brickType : bt
      ));
    } else {
      // Add new brick type
      setBrickTypes([...brickTypes, brickType]);
    }
    setShowModal(false);
  };

  const handleCloseModal = () => {
    setShowModal(false);
    setEditingBrickType(null);
  };

  return (
    <Layout title="Quản lý dòng gạch">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '30px' }}>
        <h2 style={{ fontSize: '20px', fontWeight: '600', color: '#2c3e50' }}>
          Danh sách dòng gạch
        </h2>
        <Button className="btn-primary" onClick={handleAddNew}>
          <span>+</span> Thêm dòng gạch mới
        </Button>
      </div>

      <div className="section-card">
        <div className="brick-types-table-wrapper">
          <BrickTypeTable
            brickTypes={brickTypes}
            onEdit={handleEdit}
            onDelete={handleDelete}
          />
        </div>
      </div>

      {showModal && (
        <BrickTypeModal
          brickType={editingBrickType}
          workshops={mockWorkshops}
          productionLines={mockProductionLines}
          onSave={handleSave}
          onClose={handleCloseModal}
        />
      )}
    </Layout>
  );
}